### ISSUE TITLE
git.exc.InvalidGitRepositoryError

### ISSUE THREAD

**Issue by GabLeRoux** [jianli/git-playback#8]
Within a git directory;

```
 git-playback some_file
```

```
Traceback (most recent call last):
  File "/usr/bin/git-playback", line 11, in <module>
    load_entry_point('git-playback==0.1.1rc0', 'console_scripts', 'git-playback')()
  File "/usr/lib/python3.5/site-packages/playback/__init__.py", line 145, in playback
    curses.wrapper(function)
  File "/usr/lib/python3.5/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/lib/python3.5/site-packages/playback/__init__.py", line 50, in function
    repo = git.Repo(os.getcwd())
  File "/usr/lib/python3.5/site-packages/git/repo/base.py", line 171, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: <snip>/some/folder
```

```
python --version
Python 3.5.2
```

```
pip freeze | grep playback
git-playback==0.1.1rc0
```

**Comment by GabLeRoux** [comment]
Ah ok, got it, I had to be in the same directory as the `.git` folder. Closing issue. Thanks for that tool btw! Would be cool to allow command to work within **sub folders**.

**Comment by GabLeRoux** [comment]
Ah this could probably solve current issue (did't try tho):
https://github.com/jianli/git-playback/pull/6/commits/de29907c804df925c2e82763df5ab39b7955cbb3
